name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-14]   # add windows-latest if you want
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y ninja-build
          else
            brew update
            brew install ninja || true
          fi

      - name: Configure (preset=dev)
        run: cmake --preset dev

      - name: Build
        run: cmake --build --preset dev -j

      - name: Run tests
        run: ctest --preset dev --output-on-failure